<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <id>Beztek.Facade.Storage</id>
    <version>1.2.9</version>
    <authors>Peter Thomas</authors>
    <owners>Beztek Software Solutions</owners>
    <projectUrl>https://github.com/Beztek-Software-Solutions/storage-facade</projectUrl>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <description>Storage Facade</description>
    <releaseNotes>Storage Facade</releaseNotes>
    <copyright>Copyright 2023, Beztek Software Solutions</copyright>
    <tags>Beztek.Facade;Beztek.Facade.Storage;storage-facade;StorageFacadeFacade</tags>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.101.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageReference Include="MimeTypeMapOfficial" Version="1.0.17" />
    <PackageReference Include="SMBLibrary" Version="1.5.7.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\README.md" Pack="true" PackagePath="" />
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Beztek.Facade.Storage.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
